### ISSUE TITLE
Add Loading Notifications for Loading Events

### ISSUE THREAD

**Issue by churay** [churay/ytpa#26]
The tool should be extended so that all user queries that require nontrivial processing (e.g. querying the video data for a playlist) are displayed in some way to the user.  The user should also be notified when these queries are completed so that they know when they can continue using the tool.

**Comment by timchow** [comment]
Resolved with commit 4e3a49a4e1b9e8959e481ba53b404690c319e520

**Comment by churay** [comment]
If possible, the solution for this should be changed so that the graph visualization panel doesn't have a nested well.  Since it seems like we're going to move the spinner to one of the selector anyway, this probably won't be an issue in the end.

**Comment by churay** [comment]
Added with the changes in commit 9a2820dc4d78945063264d6e0a149d416be9ea38.
