### ISSUE TITLE
Querying Video Items from Certain Playlists Yields Invalid Results

### ISSUE THREAD

**Issue by churay** [churay/ytpa#9]
Attempting to query the list of videos contained within some playlists causes the querying function to return a result with one or more invalid items.  This behavior can be observed by attempting to query the "Super Mario Maker" playlist on the "Game Grumps" YouTube channel and several of the playlists on the "Makiplier" channel.  This bug should be fixed so that queries on all playlists return a valid set of video results.

**Comment by timchow** [comment]
Fixed with commit 3da8a45ec34773658f16a58bb34bad8e286e540a
